// Generated by tools/generate_v23_pickup_contract.py; do not edit.
// Narrow W01.1 metadata, not a generated HTTP client or endpoint implementation.
export const v23PickupSourceSha256 = "35b75c1b7d36e67403a2981ed0f0f927548f017db8aeffe40a4c297a0b1de7ff";
export const v23PickupErrorCodes = [
  "COMPLETE_ORDER_REQUIRED",
  "CUSTODY_MISMATCH",
  "EXECUTION_FENCE_CHANGED",
  "IDEMPOTENCY_CONFLICT",
  "IMMUTABLE_RECORD",
  "INBOUND_DISCREPANCY",
  "INBOUND_NOT_RECEIVED",
  "MANIFEST_MISMATCH",
  "NOT_AUTHORIZED",
  "PICKUP_NOT_READY",
  "QUANTITY_ALREADY_ALLOCATED",
  "QUANTITY_EXCEEDED",
  "STALE_VERSION",
  "VALIDATION_FAILED"
] as const;
export type V23PickupErrorCode = (typeof v23PickupErrorCodes)[number];
export const v23PickupRequiredRoots = [
  {
    "payload_field": "round_id",
    "aggregate_type": "rounds",
    "when": "required"
  },
  {
    "payload_field": "pickup_stop_id",
    "aggregate_type": "stops",
    "when": "required"
  },
  {
    "payload_field": "manifest_ids[]",
    "aggregate_type": "manifests",
    "when": "each supplied existing ID"
  },
  {
    "payload_field": "fulfillment_unit_ids[]",
    "aggregate_type": "fulfillment_units",
    "when": "every selected existing ID"
  }
] as const;
