-- V2.3-r1 role/policy baseline. Apply after the invariant files using a migration administrator.
-- 2026-09-08: full PostGIS execution found the trail policy referenced a different
-- table. Check location_samples timestamps in its own entitlement window.
CREATE ROLE rounds_api NOLOGIN NOSUPERUSER NOBYPASSRLS;
CREATE ROLE rounds_broker NOLOGIN NOSUPERUSER NOBYPASSRLS;
GRANT USAGE ON SCHEMA rounds TO rounds_api, rounds_broker;
CREATE OR REPLACE FUNCTION rounds.context_tenant() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('rounds.tenant_id',true),'')::uuid $$;
CREATE OR REPLACE FUNCTION rounds.context_principal() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('rounds.principal_id',true),'')::uuid $$;
CREATE OR REPLACE FUNCTION rounds.context_city() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('rounds.city_id',true),'')::uuid $$;
CREATE POLICY tenant_scope ON rounds.memberships TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.memberships TO rounds_api;
CREATE POLICY tenant_scope ON rounds.cities TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.cities TO rounds_api;
CREATE POLICY tenant_scope ON rounds.city_grants TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.city_grants TO rounds_api;
CREATE POLICY tenant_scope ON rounds.brands TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.brands TO rounds_api;
CREATE POLICY tenant_scope ON rounds.sites TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.sites TO rounds_api;
CREATE POLICY tenant_scope ON rounds.feature_entitlements TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.feature_entitlements TO rounds_api;
CREATE POLICY tenant_scope ON rounds.policy_versions TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT ON rounds.policy_versions TO rounds_api;
CREATE POLICY tenant_scope ON rounds.policy_bindings TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.policy_bindings TO rounds_api;
CREATE POLICY tenant_scope ON rounds.tenant_subscriptions TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.tenant_subscriptions TO rounds_api;
CREATE POLICY tenant_scope ON rounds.usage_ledger TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT ON rounds.usage_ledger TO rounds_api;
CREATE POLICY tenant_scope ON rounds.driver_relationships TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.driver_relationships TO rounds_api;
CREATE POLICY tenant_scope ON rounds.invitations TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.invitations TO rounds_api;
CREATE POLICY tenant_scope ON rounds.driver_contact_permissions TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.driver_contact_permissions TO rounds_api;
CREATE POLICY tenant_scope ON rounds.availability_requests TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.availability_requests TO rounds_api;
CREATE POLICY tenant_scope ON rounds.cargo_classes TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.cargo_classes TO rounds_api;
CREATE POLICY tenant_scope ON rounds.vehicle_profiles TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.vehicle_profiles TO rounds_api;
CREATE POLICY tenant_scope ON rounds.profile_cargo_limits TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.profile_cargo_limits TO rounds_api;
CREATE POLICY tenant_scope ON rounds.handling_rules TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.handling_rules TO rounds_api;
CREATE POLICY tenant_scope ON rounds.vehicles TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.vehicles TO rounds_api;
CREATE POLICY tenant_scope ON rounds.shift_templates TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.shift_templates TO rounds_api;
CREATE POLICY tenant_scope ON rounds.shift_occurrences TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.shift_occurrences TO rounds_api;
CREATE POLICY tenant_scope ON rounds.attendance_events TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT ON rounds.attendance_events TO rounds_api;
CREATE POLICY tenant_scope ON rounds.slot_templates TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.slot_templates TO rounds_api;
CREATE POLICY tenant_scope ON rounds.slot_template_versions TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT ON rounds.slot_template_versions TO rounds_api;
CREATE POLICY tenant_scope ON rounds.slot_overrides TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.slot_overrides TO rounds_api;
CREATE POLICY tenant_scope ON rounds.slot_occurrences TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.slot_occurrences TO rounds_api;
CREATE POLICY tenant_scope ON rounds.slot_reservations TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.slot_reservations TO rounds_api;
CREATE POLICY tenant_scope ON rounds.source_connections TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.source_connections TO rounds_api;
CREATE POLICY tenant_scope ON rounds.source_events TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.source_events TO rounds_api;
CREATE POLICY tenant_scope ON rounds.intake_batches TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.intake_batches TO rounds_api;
CREATE POLICY tenant_scope ON rounds.intake_drafts TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.intake_drafts TO rounds_api;
CREATE POLICY tenant_scope ON rounds.address_suggestions TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.address_suggestions TO rounds_api;
CREATE POLICY tenant_scope ON rounds.entrances TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.entrances TO rounds_api;
CREATE POLICY tenant_scope ON rounds.entrance_revisions TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT ON rounds.entrance_revisions TO rounds_api;
CREATE POLICY tenant_scope ON rounds.location_observations TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.location_observations TO rounds_api;
CREATE POLICY tenant_scope ON rounds.deliveries TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.deliveries TO rounds_api;
CREATE POLICY tenant_scope ON rounds.delivery_contacts TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.delivery_contacts TO rounds_api;
CREATE POLICY tenant_scope ON rounds.manifests TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.manifests TO rounds_api;
CREATE POLICY tenant_scope ON rounds.manifest_lines TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.manifest_lines TO rounds_api;
CREATE POLICY tenant_scope ON rounds.packages TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.packages TO rounds_api;
CREATE POLICY tenant_scope ON rounds.package_contents TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.package_contents TO rounds_api;
CREATE POLICY tenant_scope ON rounds.plans TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.plans TO rounds_api;
CREATE POLICY tenant_scope ON rounds.plan_proposals TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT ON rounds.plan_proposals TO rounds_api;
CREATE POLICY tenant_scope ON rounds.plan_releases TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT ON rounds.plan_releases TO rounds_api;
CREATE POLICY tenant_scope ON rounds.rounds TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.rounds TO rounds_api;
CREATE POLICY tenant_scope ON rounds.stops TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.stops TO rounds_api;
CREATE POLICY tenant_scope ON rounds.assignments TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.assignments TO rounds_api;
CREATE POLICY tenant_scope ON rounds.active_delivery_claims TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.active_delivery_claims TO rounds_api;
CREATE POLICY tenant_scope ON rounds.delivery_attempts TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.delivery_attempts TO rounds_api;
CREATE POLICY tenant_scope ON rounds.custody_events TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT ON rounds.custody_events TO rounds_api;
CREATE POLICY tenant_scope ON rounds.custody_event_lines TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT ON rounds.custody_event_lines TO rounds_api;
CREATE POLICY tenant_scope ON rounds.custody_balances TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.custody_balances TO rounds_api;
CREATE POLICY tenant_scope ON rounds.handoffs TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.handoffs TO rounds_api;
CREATE POLICY tenant_scope ON rounds.assets TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.assets TO rounds_api;
CREATE POLICY tenant_scope ON rounds.proof_submissions TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.proof_submissions TO rounds_api;
CREATE POLICY tenant_scope ON rounds.proof_items TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.proof_items TO rounds_api;
CREATE POLICY tenant_scope ON rounds.issues TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.issues TO rounds_api;
CREATE POLICY tenant_scope ON rounds.issue_decisions TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT ON rounds.issue_decisions TO rounds_api;
CREATE POLICY tenant_scope ON rounds.return_tasks TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.return_tasks TO rounds_api;
CREATE POLICY tenant_scope ON rounds.change_proposals TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.change_proposals TO rounds_api;
CREATE POLICY tenant_scope ON rounds.change_responses TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT ON rounds.change_responses TO rounds_api;
CREATE POLICY tenant_scope ON rounds.broadcasts TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.broadcasts TO rounds_api;
CREATE POLICY tenant_scope ON rounds.broadcast_waves TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.broadcast_waves TO rounds_api;
CREATE POLICY tenant_scope ON rounds.offers TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.offers TO rounds_api;
CREATE POLICY tenant_scope ON rounds.freelance_agreements TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.freelance_agreements TO rounds_api;
CREATE POLICY tenant_scope ON rounds.fare_adjustments TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT ON rounds.fare_adjustments TO rounds_api;
CREATE POLICY tenant_scope ON rounds.settlement_records TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.settlement_records TO rounds_api;
CREATE POLICY tenant_scope ON rounds.settlement_events TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT ON rounds.settlement_events TO rounds_api;
CREATE POLICY tenant_scope ON rounds.transport_trips TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.transport_trips TO rounds_api;
CREATE POLICY tenant_scope ON rounds.trip_bookings TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.trip_bookings TO rounds_api;
CREATE POLICY tenant_scope ON rounds.trip_receipts TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT ON rounds.trip_receipts TO rounds_api;
CREATE POLICY tenant_scope ON rounds.conversations TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.conversations TO rounds_api;
CREATE POLICY tenant_scope ON rounds.conversation_participants TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.conversation_participants TO rounds_api;
CREATE POLICY tenant_scope ON rounds.messages TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.messages TO rounds_api;
CREATE POLICY tenant_scope ON rounds.message_attachments TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.message_attachments TO rounds_api;
CREATE POLICY tenant_scope ON rounds.message_receipts TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.message_receipts TO rounds_api;
CREATE POLICY tenant_scope ON rounds.call_sessions TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.call_sessions TO rounds_api;
CREATE POLICY tenant_scope ON rounds.call_events TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT ON rounds.call_events TO rounds_api;
CREATE POLICY tenant_scope ON rounds.notifications TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.notifications TO rounds_api;
CREATE POLICY tenant_scope ON rounds.customer_tracking_tokens TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.customer_tracking_tokens TO rounds_api;
CREATE POLICY tenant_scope ON rounds.notification_deliveries TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.notification_deliveries TO rounds_api;
CREATE POLICY tenant_scope ON rounds.provider_receipts TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT ON rounds.provider_receipts TO rounds_api;
CREATE POLICY tenant_scope ON rounds.writeback_tasks TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.writeback_tasks TO rounds_api;
CREATE POLICY tenant_scope ON rounds.route_estimates TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.route_estimates TO rounds_api;
CREATE POLICY tenant_scope ON rounds.navigation_intents TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.navigation_intents TO rounds_api;
CREATE POLICY tenant_scope ON rounds.route_trails TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.route_trails TO rounds_api;
CREATE POLICY tenant_scope ON rounds.domain_events TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT ON rounds.domain_events TO rounds_api;
CREATE POLICY tenant_scope ON rounds.outbox_events TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.outbox_events TO rounds_api;
CREATE POLICY tenant_scope ON rounds.audit_access TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT ON rounds.audit_access TO rounds_api;
CREATE POLICY tenant_scope ON rounds.export_jobs TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.export_jobs TO rounds_api;
CREATE POLICY tenant_scope ON rounds.privacy_requests TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.privacy_requests TO rounds_api;
CREATE POLICY tenant_scope ON rounds.retention_holds TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.retention_holds TO rounds_api;
CREATE POLICY tenant_scope ON rounds.slot_occurrence_bindings TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.slot_occurrence_bindings TO rounds_api;
CREATE POLICY tenant_scope ON rounds.custodians TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.custodians TO rounds_api;
CREATE POLICY tenant_scope ON rounds.custody_transfers TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.custody_transfers TO rounds_api;
CREATE POLICY tenant_scope ON rounds.custody_transfer_lines TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.custody_transfer_lines TO rounds_api;
CREATE POLICY tenant_scope ON rounds.return_task_lines TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.return_task_lines TO rounds_api;
CREATE POLICY tenant_scope ON rounds.trip_booking_lines TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.trip_booking_lines TO rounds_api;
CREATE POLICY tenant_scope ON rounds.remaining_obligations TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.remaining_obligations TO rounds_api;
CREATE POLICY tenant_scope ON rounds.remaining_obligation_lines TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.remaining_obligation_lines TO rounds_api;
CREATE POLICY tenant_scope ON rounds.inbound_dependencies TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.inbound_dependencies TO rounds_api;
CREATE POLICY tenant_scope ON rounds.realtime_grants TO rounds_api USING (tenant_id=rounds.context_tenant()) WITH CHECK (tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.realtime_grants TO rounds_api;
CREATE POLICY account_scope ON rounds.principals TO rounds_api USING (id=rounds.context_principal()) WITH CHECK (id=rounds.context_principal());
GRANT SELECT, INSERT, UPDATE ON rounds.principals TO rounds_api;
CREATE POLICY account_scope ON rounds.drivers TO rounds_api USING (principal_id=rounds.context_principal()) WITH CHECK (principal_id=rounds.context_principal());
GRANT SELECT, INSERT, UPDATE ON rounds.drivers TO rounds_api;
CREATE POLICY account_scope ON rounds.onboarding_drafts TO rounds_api USING (principal_id=rounds.context_principal()) WITH CHECK (principal_id=rounds.context_principal());
GRANT SELECT, INSERT, UPDATE ON rounds.onboarding_drafts TO rounds_api;
CREATE POLICY account_scope ON rounds.account_events TO rounds_api USING (principal_id=rounds.context_principal()) WITH CHECK (principal_id=rounds.context_principal());
GRANT SELECT, INSERT ON rounds.account_events TO rounds_api;
-- 2026-09-08 transaction implementation: same actor may belong to several tenants/cities;
-- receipt access requires the original selected scope, not just actor identity.
CREATE POLICY account_scope ON rounds.command_receipts TO rounds_api USING (actor_id=rounds.context_principal() AND tenant_id IS NOT DISTINCT FROM rounds.context_tenant() AND city_id IS NOT DISTINCT FROM rounds.context_city()) WITH CHECK (actor_id=rounds.context_principal() AND tenant_id IS NOT DISTINCT FROM rounds.context_tenant() AND city_id IS NOT DISTINCT FROM rounds.context_city());
GRANT SELECT, INSERT, UPDATE ON rounds.command_receipts TO rounds_api;
CREATE POLICY account_scope ON rounds.availability_declarations TO rounds_api USING (driver_id IN (SELECT id FROM rounds.drivers WHERE principal_id=rounds.context_principal())) WITH CHECK (driver_id IN (SELECT id FROM rounds.drivers WHERE principal_id=rounds.context_principal()));
GRANT SELECT, INSERT, UPDATE ON rounds.availability_declarations TO rounds_api;
CREATE POLICY account_scope ON rounds.driver_devices TO rounds_api USING (driver_id IN (SELECT id FROM rounds.drivers WHERE principal_id=rounds.context_principal())) WITH CHECK (driver_id IN (SELECT id FROM rounds.drivers WHERE principal_id=rounds.context_principal()));
GRANT SELECT, INSERT, UPDATE ON rounds.driver_devices TO rounds_api;
CREATE POLICY account_scope ON rounds.verification_applications TO rounds_api USING (driver_id IN (SELECT id FROM rounds.drivers WHERE principal_id=rounds.context_principal())) WITH CHECK (driver_id IN (SELECT id FROM rounds.drivers WHERE principal_id=rounds.context_principal()));
GRANT SELECT, INSERT, UPDATE ON rounds.verification_applications TO rounds_api;
CREATE POLICY account_scope ON rounds.payout_methods TO rounds_api USING (driver_id IN (SELECT id FROM rounds.drivers WHERE principal_id=rounds.context_principal())) WITH CHECK (driver_id IN (SELECT id FROM rounds.drivers WHERE principal_id=rounds.context_principal()));
GRANT SELECT, INSERT, UPDATE ON rounds.payout_methods TO rounds_api;
CREATE POLICY account_scope ON rounds.freelance_vehicles TO rounds_api USING (driver_id IN (SELECT id FROM rounds.drivers WHERE principal_id=rounds.context_principal())) WITH CHECK (driver_id IN (SELECT id FROM rounds.drivers WHERE principal_id=rounds.context_principal()));
GRANT SELECT, INSERT, UPDATE ON rounds.freelance_vehicles TO rounds_api;
CREATE POLICY account_scope ON rounds.current_positions TO rounds_api USING (driver_id IN (SELECT id FROM rounds.drivers WHERE principal_id=rounds.context_principal())) WITH CHECK (driver_id IN (SELECT id FROM rounds.drivers WHERE principal_id=rounds.context_principal()));
GRANT SELECT, INSERT, UPDATE ON rounds.current_positions TO rounds_api;
CREATE POLICY account_scope ON rounds.location_samples TO rounds_api USING (driver_id IN (SELECT id FROM rounds.drivers WHERE principal_id=rounds.context_principal())) WITH CHECK (driver_id IN (SELECT id FROM rounds.drivers WHERE principal_id=rounds.context_principal()));
GRANT SELECT, INSERT, UPDATE ON rounds.location_samples TO rounds_api;
-- Global broker operations: service-role connection only, never assigned to browser/native clients.
CREATE POLICY broker_scope ON rounds.tenants TO rounds_broker USING (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on') WITH CHECK (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on');
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.tenants TO rounds_broker;
CREATE POLICY broker_scope ON rounds.principals TO rounds_broker USING (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on') WITH CHECK (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on');
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.principals TO rounds_broker;
CREATE POLICY broker_scope ON rounds.drivers TO rounds_broker USING (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on') WITH CHECK (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on');
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.drivers TO rounds_broker;
CREATE POLICY broker_scope ON rounds.driver_devices TO rounds_broker USING (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on') WITH CHECK (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on');
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.driver_devices TO rounds_broker;
CREATE POLICY broker_scope ON rounds.onboarding_drafts TO rounds_broker USING (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on') WITH CHECK (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on');
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.onboarding_drafts TO rounds_broker;
CREATE POLICY broker_scope ON rounds.verification_applications TO rounds_broker USING (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on') WITH CHECK (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on');
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.verification_applications TO rounds_broker;
CREATE POLICY broker_scope ON rounds.verification_evidence TO rounds_broker USING (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on') WITH CHECK (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on');
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.verification_evidence TO rounds_broker;
CREATE POLICY broker_scope ON rounds.payout_methods TO rounds_broker USING (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on') WITH CHECK (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on');
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.payout_methods TO rounds_broker;
CREATE POLICY broker_scope ON rounds.availability_declarations TO rounds_broker USING (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on') WITH CHECK (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on');
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.availability_declarations TO rounds_broker;
CREATE POLICY broker_scope ON rounds.vehicle_types TO rounds_broker USING (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on') WITH CHECK (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on');
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.vehicle_types TO rounds_broker;
CREATE POLICY broker_scope ON rounds.freelance_vehicles TO rounds_broker USING (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on') WITH CHECK (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on');
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.freelance_vehicles TO rounds_broker;
CREATE POLICY broker_scope ON rounds.driver_commitments TO rounds_broker USING (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on') WITH CHECK (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on');
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.driver_commitments TO rounds_broker;
CREATE POLICY broker_scope ON rounds.tracking_entitlements TO rounds_broker USING (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on') WITH CHECK (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on');
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.tracking_entitlements TO rounds_broker;
CREATE POLICY broker_scope ON rounds.current_positions TO rounds_broker USING (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on') WITH CHECK (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on');
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.current_positions TO rounds_broker;
CREATE POLICY broker_scope ON rounds.location_samples TO rounds_broker USING (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on') WITH CHECK (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on');
GRANT SELECT, INSERT ON rounds.location_samples TO rounds_broker;
CREATE POLICY broker_scope ON rounds.command_receipts TO rounds_broker USING (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on') WITH CHECK (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on');
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.command_receipts TO rounds_broker;
CREATE POLICY broker_scope ON rounds.job_runs TO rounds_broker USING (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on') WITH CHECK (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on');
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.job_runs TO rounds_broker;
CREATE POLICY broker_scope ON rounds.consumer_receipts TO rounds_broker USING (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on') WITH CHECK (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on');
GRANT SELECT, INSERT ON rounds.consumer_receipts TO rounds_broker;
CREATE POLICY broker_scope ON rounds.account_events TO rounds_broker USING (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on') WITH CHECK (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on');
GRANT SELECT, INSERT ON rounds.account_events TO rounds_broker;
CREATE POLICY broker_scope ON rounds.account_outbox TO rounds_broker USING (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on') WITH CHECK (rounds.context_principal() IS NOT NULL AND nullif(current_setting('rounds.broker_authorized',true),'')='on');
GRANT SELECT, INSERT, UPDATE, DELETE ON rounds.account_outbox TO rounds_broker;
-- The deployment connection role may SET ROLE rounds_api or rounds_broker only inside reviewed server handlers.
-- Policy alone cannot make an untrusted arbitrary-SQL connection safe; the service controls context and credentials.
CREATE POLICY tenant_scope ON rounds.agreement_revisions TO rounds_api USING(tenant_id=rounds.context_tenant()) WITH CHECK(tenant_id=rounds.context_tenant());
GRANT SELECT, INSERT ON rounds.agreement_revisions TO rounds_api;

-- V2.1: trusted server creates grants; API only reads them.
CREATE ROLE rounds_entitlements NOLOGIN NOSUPERUSER NOBYPASSRLS;
GRANT USAGE ON SCHEMA rounds TO rounds_entitlements;
GRANT SELECT,INSERT,UPDATE,DELETE ON rounds.driver_tracking_grants TO rounds_entitlements;
CREATE POLICY grant_manager ON rounds.driver_tracking_grants TO rounds_entitlements USING(tenant_id=rounds.context_tenant()) WITH CHECK(tenant_id=rounds.context_tenant());
GRANT SELECT ON rounds.driver_tracking_grants TO rounds_api;
CREATE POLICY grant_reader ON rounds.driver_tracking_grants FOR SELECT TO rounds_api USING(tenant_id=rounds.context_tenant());
CREATE POLICY related_driver ON rounds.drivers FOR SELECT TO rounds_api USING(
 EXISTS(SELECT 1 FROM rounds.driver_relationships r WHERE r.tenant_id=rounds.context_tenant() AND r.driver_id=drivers.id AND r.status='active')
 OR EXISTS(SELECT 1 FROM rounds.freelance_agreements f WHERE f.tenant_id=rounds.context_tenant() AND f.driver_id=drivers.id AND f.state IN ('active','disputed')));
CREATE POLICY entitled_position ON rounds.current_positions FOR SELECT TO rounds_api USING(EXISTS(SELECT 1 FROM rounds.driver_tracking_grants g WHERE g.tenant_id=rounds.context_tenant() AND g.driver_id=current_positions.driver_id AND g.tracking_entitlement_id=current_positions.tracking_entitlement_id AND EXISTS(SELECT 1 FROM rounds.tracking_entitlements e WHERE e.id=g.tracking_entitlement_id AND e.tenant_id=g.tenant_id AND e.driver_id=g.driver_id AND e.revoked_at IS NULL AND now()>=e.starts_at AND (e.ends_at IS NULL OR now()<e.ends_at)) AND current_positions.observed_at>=g.starts_at AND current_positions.observed_at<g.ends_at AND g.revoked_at IS NULL AND now()>=g.starts_at AND now()<g.ends_at));
CREATE POLICY entitled_trail ON rounds.location_samples FOR SELECT TO rounds_api USING(EXISTS(SELECT 1 FROM rounds.driver_tracking_grants g WHERE g.tenant_id=rounds.context_tenant() AND g.driver_id=location_samples.driver_id AND g.tracking_entitlement_id=location_samples.tracking_entitlement_id AND EXISTS(SELECT 1 FROM rounds.tracking_entitlements e WHERE e.id=g.tracking_entitlement_id AND e.tenant_id=g.tenant_id AND e.driver_id=g.driver_id AND e.revoked_at IS NULL AND now()>=e.starts_at AND location_samples.observed_at>=e.starts_at AND (e.ends_at IS NULL OR (now()<e.ends_at AND location_samples.observed_at<e.ends_at))) AND g.revoked_at IS NULL AND now()>=g.starts_at AND now()<g.ends_at AND location_samples.observed_at>=g.starts_at AND location_samples.observed_at<g.ends_at));
DROP POLICY tenant_scope ON rounds.notifications;
CREATE POLICY notification_self ON rounds.notifications TO rounds_api USING(tenant_id=rounds.context_tenant() AND principal_id=rounds.context_principal()) WITH CHECK(tenant_id=rounds.context_tenant() AND principal_id=rounds.context_principal());
GRANT SELECT ON rounds.tenants,rounds.vehicle_types TO rounds_api;
CREATE POLICY current_tenant ON rounds.tenants FOR SELECT TO rounds_api USING(id=rounds.context_tenant());
CREATE POLICY vehicle_reference ON rounds.vehicle_types FOR SELECT TO rounds_api USING(rounds.context_principal() IS NOT NULL);
-- Driver principal labels are permitted only through readable driver relationships, not all principals.
CREATE POLICY related_driver_label ON rounds.principals FOR SELECT TO rounds_api USING(EXISTS(SELECT 1 FROM rounds.drivers d WHERE d.principal_id=principals.id));
