"""Generate the narrow native registration schema closure, not a full Dart API."""
from pathlib import Path
import hashlib
import json
import sys

ROOT = Path(__file__).resolve().parents[1]
source = ROOT / 'specs/source/Rounds-Complete-Project-v2.3/specs/contracts/openapi.json'
schemas = json.loads(source.read_text())['components']['schemas']
names = ['DriverDeviceSessionRequest', 'DriverDeviceRevokeRequest',
         'DriverDeviceSessionResult', 'DriverDeviceRevokeResult']
selected = {name: schemas[name] for name in names}
# The native validator intentionally supports only these flat contracts. Fail
# generation if a later contract needs a richer validator; never ignore it.
for schema in selected.values():
    assert set(schema) == {'type', 'additionalProperties', 'required', 'properties'}
    assert schema['type'] == 'object' and schema['additionalProperties'] is False
    assert set(schema['required']) == set(schema['properties'])
    for prop in schema['properties'].values():
        assert set(prop) <= {'type', 'pattern', 'writeOnly', 'enum', 'format', 'minimum', 'maximum', 'maxLength', 'const'}
        assert prop.get('type') in ('string', 'integer') or prop == {'const': True}
        assert prop.get('format') in (None, 'uuid', 'date-time')
        if prop.get('type') == 'integer':
            assert 'minimum' in prop and 'maximum' in prop
target = ROOT / 'apps/driver_harness/lib/src/v23/generated/device_wire.g.dart'
output = ('// Generated by tools/generate_v23_device_wire.py; do not edit.\n'
          '// Exact flat registration schemas; no endpoint activation.\n'
          f"const deviceWireSourceSha256 = '{hashlib.sha256(source.read_bytes()).hexdigest()}';\n"
          "const deviceWireSchemaJson = r'''\n" + json.dumps(selected, indent=2) + "\n''';\n")
if '--check' in sys.argv:
    assert target.exists() and target.read_text() == output, 'Regenerate native device wire contracts'
    print('PASS exact native device wire schemas')
else:
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(output)
    print('Generated four native device wire schemas')
