"""Generate command/error names from the active contracts; no handwritten enum copy."""
from pathlib import Path
import hashlib
import json
import sys

root = Path(__file__).resolve().parents[1]
source = root / 'specs/source/Rounds-Complete-Project-v2.3/specs/contracts'
catalog = source / 'COMMAND-CATALOG.json'
api = source / 'openapi.json'
names = [c['name'] for c in json.loads(catalog.read_text())]
errors = json.loads(api.read_text())['components']['schemas']['Error']['properties']['code']['enum']
text = ('// Generated by tools/generate_v23_command_metadata.py; not a full HTTP client.\n'
        f'// Catalogue SHA256: {hashlib.sha256(catalog.read_bytes()).hexdigest()}\n'
        f'// OpenAPI SHA256: {hashlib.sha256(api.read_bytes()).hexdigest()}\n'
        'export const v23CommandTypes = ' + json.dumps(names, indent=2) + ' as const;\n'
        'export type V23CommandType = (typeof v23CommandTypes)[number];\n'
        'export const v23ErrorCodes = ' + json.dumps(errors, indent=2) + ' as const;\n'
        'export type V23ErrorCode = (typeof v23ErrorCodes)[number];\n')
target = root / 'packages/contracts/src/v23/command-metadata.ts'
if '--check' in sys.argv:
    assert target.is_file() and target.read_text() == text, 'Regenerate v23 command metadata'
    print('PASS v23 command/error metadata')
else:
    target.write_text(text)
    print('Generated v23 command/error metadata')
