"""Mirror the clean local SQL verbatim; do not apply it to Driver schema5."""
from pathlib import Path
import hashlib
import sys

root = Path(__file__).resolve().parents[1]
source = root / 'specs/source/Rounds-Complete-Project-v2.3/specs/database/DRIVER-LOCAL-SCHEMA.sql'
target = root / 'apps/driver_harness/lib/src/v23/generated/local_schema.g.dart'
sql = source.read_text()
assert "'''" not in sql and '$' not in sql
digest = hashlib.sha256(source.read_bytes()).hexdigest()
output = '// Generated by tools/generate_v23_local_schema.py. Not a legacy migration.\n'
output += f"const localSchemaSha256 = '{digest}';\nconst localSchemaSql = r'''\n{sql}''';\n"
if '--check' in sys.argv:
    assert target.read_text() == output, 'Stale local SQL mirror'
else:
    target.write_text(output)
print('PASS local SQL mirror: 14 reference tables; legacy schema5 untouched')
