"""Extract the exact pickup schema closure and TS types; no legacy client rewrite."""
from pathlib import Path
import hashlib
import json
import sys

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / 'specs/source/Rounds-Complete-Project-v2.3/specs/contracts'
selected = {}
hashes = {}
for filename, roots in [('openapi.json', ['ConfirmPickupRequest', 'ConfirmPickupResult', 'ConfirmArrivalRequest', 'ConfirmArrivalResult', 'RecordHandoffRequest', 'RecordHandoffResult', 'ReserveAssetRequest', 'ReserveAssetResult', 'VerifyAssetRequest', 'VerifyAssetResult', 'RejectedCommandStatus', 'CommandStatusQueryResult',
                                        'SubmitProofRequest', 'SubmitProofResult', 'CompleteDeliveryRequest', 'CompleteDeliveryResult', 'ReportIssueRequest', 'ReportIssueResult', 'DriverDeviceSessionRequest', 'DriverDeviceRevokeRequest', 'DriverDeviceSessionResult', 'DriverDeviceRevokeResult', 'DriverDeviceSecurityAudit', 'DriverRoundExecutionQueryResult', 'DriverRoundPickupQueryResult', 'DriverPickupIssueQueryResult']),
                        ('events.json', ['Event_pickup_confirmed', 'Event_handoff_recorded', 'Event_stop_arrived', 'Event_asset_reserved', 'Event_asset_verified', 'Event_proof_submitted', 'Event_fulfillment_completed', 'Event_delivery_completed', 'Event_round_completed', 'Event_issue_reported', 'Event_round_readiness_changed'])]:
    if filename == 'openapi.json':
        roots += ['ResolveIssueRequest', 'ResolveIssueResult', 'OperationsPickupIssuesQueryResult', 'OperationsDeliveryBoardQueryResult', 'SaveDeliveryDraftRequest', 'SaveDeliveryDraftResult', 'OperationsManualIntakeQueryResult', 'ReviewAddressRequest', 'ReviewAddressResult']
    else:
        roots += ['Event_issue_decided', 'Event_intake_draft_saved', 'Event_address_reviewed']
    path = BASE / filename
    hashes[filename] = hashlib.sha256(path.read_bytes()).hexdigest()
    schemas = json.loads(path.read_text())['components']['schemas']
    if filename == 'openapi.json':
        # The implemented status endpoint is a strict subset of CommandResult,
        # not a claim that all 131 command result handlers have been generated.
        variants = [{'$ref': '#/components/schemas/' + name}
                    for name in ['ConfirmPickupResult', 'ConfirmArrivalResult', 'RecordHandoffResult', 'ReserveAssetResult', 'VerifyAssetResult', 'SubmitProofResult', 'CompleteDeliveryResult', 'ReportIssueResult', 'RejectedCommandStatus']]
        variants.append({'$ref': '#/components/schemas/ResolveIssueResult'})
        variants.append({'$ref': '#/components/schemas/SaveDeliveryDraftResult'})
        variants.append({'$ref': '#/components/schemas/ReviewAddressResult'})
        assert all(v in schemas['CommandResult']['oneOf'] for v in variants)
        schemas['CommandResult'] = {'oneOf': variants}
    def visit(name):
        value = schemas[name]
        if name in selected:
            assert selected[name] == value, f'Conflicting schema mirror: {name}'
            return
        selected[name] = value
        def walk(node):
            if isinstance(node, dict):
                if '$ref' in node:
                    assert node['$ref'].startswith('#/components/schemas/')
                    visit(node['$ref'].split('/')[-1])
                for item in node.values():
                    walk(item)
            elif isinstance(node, list):
                for item in node:
                    walk(item)
        walk(value)
    for name in roots:
        visit(name)

def ts(s):
    if '$ref' in s:
        return 'Wire_' + s['$ref'].split('/')[-1]
    if 'const' in s:
        return json.dumps(s['const'])
    if 'enum' in s:
        return ' | '.join(json.dumps(x) for x in s['enum'])
    for union in ['oneOf', 'anyOf']:
        if union in s and 'properties' not in s:
            return ' | '.join('(' + ts(x) + ')' for x in s[union])
    kind = s.get('type')
    if isinstance(kind, list):
        return ' | '.join(ts({**s, 'type': k}) for k in kind)
    if kind == 'object':
        return '{ ' + ' '.join(json.dumps(k) + ('' if k in s.get('required', []) else '?') + ': ' + ts(v) + ';'
                              for k, v in s['properties'].items()) + ' }'
    if kind == 'array':
        return '(' + ts(s['items']) + ')[]'
    if kind in ['string', 'boolean', 'null']:
        return kind
    if kind in ['integer', 'number']:
        return 'number'
    raise ValueError(s)

bundle = json.loads(json.dumps(selected).replace('#/components/schemas/', '#/$defs/'))
text = ('// Generated by tools/generate_v23_pickup_wire.py; do not edit.\n'
        '// Narrow wire contracts, not a public endpoint or full client.\n'
        'export const pickupWireSourceHashes = ' + json.dumps(hashes, indent=2) + ' as const;\n'
        'export const pickupWireSchemas = ' + json.dumps(bundle, indent=2) + ';\n\n'
        + '\n'.join('export type Wire_' + k + ' = ' + ts(v) + ';' for k, v in sorted(selected.items())) + '\n')
target = ROOT / 'packages/contracts/src/v23/pickup-wire.ts'
if '--check' in sys.argv:
    assert target.exists() and target.read_text() == text, 'Regenerate pickup wire contracts'
    print('PASS exact pickup wire schema closure and TS types')
else:
    target.write_text(text)
    print(f'Generated {len(selected)} pickup wire schemas/types')
