import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { Ajv2020 } from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { pickupWireSchemas } from '../packages/contracts/src/v23/pickup-wire.js';

// Build-time compilation: browser receives ordinary static validation code,
// never the schema compiler/new Function (compatible with no unsafe-eval CSP).
const names = {validBoard: 'OperationsPickupIssuesQueryResult', validDeliveryBoard: 'OperationsDeliveryBoardQueryResult', validRequest: 'ResolveIssueRequest',
  validResult: 'ResolveIssueResult', validRejected: 'RejectedCommandStatus', validError: 'Error',
  validIntake: 'OperationsManualIntakeQueryResult', validDraftRequest: 'SaveDeliveryDraftRequest', validDraftResult: 'SaveDeliveryDraftResult', validCommandStatus:'CommandStatusQueryResult'};
const selected: Record<string, any> = {};
function visit(name: string) {
  if (selected[name]) return;
  const schema = (pickupWireSchemas as Record<string, any>)[name];
  if (!schema) throw new Error('Missing schema: ' + name);
  selected[name] = schema;
  const walk = (value: any) => {
    if (!value || typeof value !== 'object') return;
    if (value.$ref) {if (!value.$ref.startsWith('#/$defs/')) throw new Error('External schema ref'); visit(value.$ref.slice(8));}
    Object.values(value).forEach(walk);
  };
  walk(schema);
}
Object.values(names).forEach(visit);
const ajv = new Ajv2020({strictTypes: false, multipleOfPrecision: 8, code: {source: true}});
addFormats(ajv);
for (const [name, schema] of Object.entries(names)) ajv.addSchema({$defs: selected, $ref: '#/$defs/' + schema}, name);
const code = standaloneCode(ajv, Object.fromEntries(Object.keys(names).map(n => [n, n])));
if (/\beval\(|new Function\b/.test(code)) throw new Error('Runtime code generation in browser validator');
const hash = createHash('sha256').update(JSON.stringify(selected)).digest('hex');
const folder = new URL('../apps/operations-web/src/v23/generated/', import.meta.url);
const outputs = {
  'operations-issue-validation.cjs': `// Generated by tools/generate_v23_operations_validators.ts. Schema SHA256 ${hash}\n${code}\n`,
  'operations-issue-validation.d.cts': '// Generated declarations; validation is performed by the companion static module.\n' + Object.keys(names).map(n => `export function ${n}(value: any): boolean;`).join('\n') + '\n',
};
if (!process.argv.includes('--check')) mkdirSync(folder, {recursive: true});
for (const [name, text] of Object.entries(outputs)) {
  const path = new URL(name, folder);
  if (process.argv.includes('--check')) {if (readFileSync(path, 'utf8') !== text) throw new Error('Stale generated validator: ' + name);}
  else writeFileSync(path, text);
}
console.log('Operations static validators: ' + Object.keys(names).length + ' checked/generated');
