"""Finite native execution commands; reject unsupported schema changes."""
from pathlib import Path
import hashlib
import json
import sys

root = Path(__file__).resolve().parents[1]
source = root / 'specs/source/Rounds-Complete-Project-v2.3/specs/contracts/openapi.json'
schemas = json.loads(source.read_text())['components']['schemas']
selected = {}
supported = {'type', '$ref', 'properties', 'required', 'additionalProperties', 'items', 'minItems', 'maxItems',
             'enum', 'const', 'minimum', 'maximum', 'exclusiveMinimum', 'multipleOf', 'format', 'description',
             'anyOf', 'minLength', 'maxLength', 'pattern'}

def visit(name):
    if name in selected:
        return
    selected[name] = schemas[name]
    def rule(s):
        assert set(s) <= supported, f'Unsupported native command keyword: {s}'
        if '$ref' in s:
            visit(s['$ref'].split('/')[-1])
        if s.get('type') == 'object':
            assert s['additionalProperties'] is False
            for p in s['properties'].values():
                rule(p)
        if 'items' in s:
            rule(s['items'])
        for branch in s.get('anyOf', []):
            rule(branch)
        assert s.get('format') in (None, 'uuid', 'date-time')
        assert s.get('multipleOf') in (None, 0.0001)
        assert s.get('pattern') in (None, '^[a-f0-9]{64}$')
        if isinstance(s.get('type'), list):
            assert s['type'] in (['number', 'null'], ['string', 'null'])
    rule(schemas[name])

for command in ('ConfirmArrival', 'ConfirmPickup', 'RecordHandoff', 'ReserveAsset', 'VerifyAsset', 'SubmitProof', 'CompleteDelivery', 'ReportIssue'):
    visit(command + 'Request')
    visit(command + 'Result')
for name in ('RejectedCommandStatus', 'PendingCommandStatus', 'Error'):
    visit(name)
# ADR-M02: the server wire includes a fresh capability, the durable receipt
# deliberately contains identity only. Derive its shape, never persist secrets.
selected['ReserveAssetReceipt'] = json.loads(json.dumps(selected['ReserveAssetResult']))
selected['ReserveAssetReceipt']['properties']['data'] = {
    'type': 'object', 'properties': {'asset_id': {'$ref': '#/components/schemas/uuid'}},
    'required': ['asset_id'], 'additionalProperties': False}
target = root / 'apps/driver_harness/lib/src/v23/generated/command_wire.g.dart'
output = ('// Generated by tools/generate_v23_native_commands.py; do not edit.\n'
          f"const commandWireSourceSha256 = '{hashlib.sha256(source.read_bytes()).hexdigest()}';\n"
          "const commandWireSchemaJson = r'''\n" + json.dumps(selected, indent=2) + "\n''';\n")
if '--check' in sys.argv:
    assert target.read_text() == output, 'Regenerate native command contracts'
    print('PASS exact native command schema closure')
else:
    target.write_text(output)
