"""Generate narrow W01.1 metadata from the active catalogue; never rewrite legacy types."""
from pathlib import Path
import hashlib
import json
import sys

root = Path(__file__).resolve().parents[1]
source = root / 'specs/source/Rounds-Complete-Project-v2.3/specs/contracts/COMMAND-CATALOG.json'
command = next(x for x in json.loads(source.read_text()) if x['name'] == 'ConfirmPickup')
target = root / 'packages/contracts/src/v23/pickup-metadata.ts'
text = ('// Generated by tools/generate_v23_pickup_contract.py; do not edit.\n'
        '// Narrow W01.1 metadata, not a generated HTTP client or endpoint implementation.\n'
        f'export const v23PickupSourceSha256 = "{hashlib.sha256(source.read_bytes()).hexdigest()}";\n'
        'export const v23PickupErrorCodes = ' + json.dumps(command['errors'], indent=2) + ' as const;\n'
        'export type V23PickupErrorCode = (typeof v23PickupErrorCodes)[number];\n'
        'export const v23PickupRequiredRoots = ' + json.dumps(command['required_roots'], indent=2) + ' as const;\n')
if '--check' in sys.argv:
    assert target.is_file() and target.read_text() == text, 'Regenerate v23 pickup metadata'
    print('PASS v23 pickup generated metadata matches active catalogue')
else:
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text)
    print('Generated v23 pickup metadata')
