"""Generate the bounded execution-view schema closure for the native reader."""
from pathlib import Path
import hashlib
import json
import sys

root = Path(__file__).resolve().parents[1]
source = root / 'specs/source/Rounds-Complete-Project-v2.3/specs/contracts/openapi.json'
schemas = json.loads(source.read_text())['components']['schemas']
selected = {}
supported = {'type', '$ref', 'properties', 'required', 'additionalProperties', 'items', 'minItems', 'maxItems',
             'enum', 'const', 'minimum', 'maximum', 'exclusiveMinimum', 'multipleOf', 'pattern', 'format', 'description'}
def visit(name):
    if name in selected:
        return
    selected[name] = schemas[name]
    def rule(s):
        assert set(s) <= supported, f'Unsupported native validation keyword: {s}'
        if '$ref' in s:
            visit(s['$ref'].split('/')[-1])
        if s.get('type') == 'object':
            assert s['additionalProperties'] is False and set(s['required']) == set(s['properties'])
            for p in s['properties'].values():
                rule(p)
        if 'items' in s:
            rule(s['items'])
        assert s.get('format') in (None, 'uuid', 'date-time')
        assert s.get('multipleOf') in (None, 0.0001), 'Native quantity precision needs explicit review'
    rule(schemas[name])
visit('DriverRoundExecutionQueryResult')
visit('DriverRoundPickupQueryResult')
visit('DriverPickupIssueQueryResult')
target = root / 'apps/driver_harness/lib/src/v23/generated/execution_wire.g.dart'
output = ('// Generated by tools/generate_v23_execution_wire.py; do not edit.\n'
          f"const executionWireSourceSha256 = '{hashlib.sha256(source.read_bytes()).hexdigest()}';\n"
          "const executionWireSchemaJson = r'''\n" + json.dumps(selected, indent=2) + "\n''';\n")
if '--check' in sys.argv:
    assert target.read_text() == output, 'Regenerate native execution contracts'
    print('PASS exact native execution schema closure')
else:
    target.write_text(output)
