"""Record source/unit/real-PG checks and optional full PostGIS fixture evidence.
No full application, shared migration or device acceptance is implied.
"""
from pathlib import Path
from datetime import datetime, timezone
import hashlib
import json
import os
import subprocess

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "specs/source/Rounds-Complete-Project-v2.3"
OUT = ROOT / "specs/build-v2.3/generated"


def hashes(paths):
    return {str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest()
            for p in sorted(set(paths)) if p.is_file()}


def main():
    env = dict(os.environ)
    deps = Path("/tmp/rounds-v23-validation-deps")
    if deps.is_dir():
        env["PYTHONPATH"] = str(deps) + (os.pathsep + env["PYTHONPATH"] if env.get("PYTHONPATH") else "")
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    tests = [str(p.relative_to(ROOT)) for folder in ["packages/domain-ts/test", "packages/contracts/test"]
             for p in sorted((ROOT / folder).glob("*.test.ts"))]
    checks = [
        ("source-publication-provenance", ["python3", "tools/test_source_reference_provenance.py"]),
        ("supplied-validator", ["python3", str((SOURCE / "specs/review/validate_package.py").relative_to(ROOT))]),
        ("reference-journeys", ["python3", str((SOURCE / "specs/review/validate_journey_examples.py").relative_to(ROOT))]),
        ("command-mirrors", ["python3", "tools/generate_v23_command_mirrors.py", "--check"]),
        ("pickup-metadata", ["python3", "tools/generate_v23_pickup_contract.py", "--check"]),
        ("pickup-wire", ["python3", "tools/generate_v23_pickup_wire.py", "--check"]),
        ("operations-static-validators", ["node", "--import", "tsx", "tools/generate_v23_operations_validators.ts", "--check"]),
        ("native-device-wire", ["python3", "tools/generate_v23_device_wire.py", "--check"]),
        ("native-execution-wire", ["python3", "tools/generate_v23_execution_wire.py", "--check"]),
        ("native-command-wire", ["python3", "tools/generate_v23_native_commands.py", "--check"]),
        ("native-local-schema", ["python3", "tools/generate_v23_local_schema.py", "--check"]),
        ("command-metadata", ["python3", "tools/generate_v23_command_metadata.py", "--check"]),
        ("domain-contracts-tests", ["node", "--import", "tsx", "--test", *tests]),
        ("domain-typecheck", ["npm", "run", "typecheck", "--workspace", "@rounds/domain-ts"]),
        ("contracts-typecheck", ["npm", "run", "typecheck", "--workspace", "@rounds/contracts"]),
        ("api-typecheck", ["npm", "run", "typecheck", "--workspace", "@rounds/api"]),
        ("operations-typecheck", ["npm", "run", "typecheck", "--workspace", "@rounds/operations-web"]),
        ("operations-tests", ["npm", "run", "test", "--workspace", "@rounds/operations-web"]),
        ("operations-production-build", ["npm", "run", "build", "--workspace", "@rounds/operations-web"]),
        ("api-and-pg-foundation-tests", ["npm", "run", "test", "--workspace", "@rounds/api"]),
    ]
    full_postgis = bool(env.get("ROUNDS_TEST_PG_BIN"))
    if full_postgis:
        checks.append(("full-postgis-schema-tests", ["npm", "run", "test:postgis", "--workspace", "@rounds/api"]))
    native = bool(env.get("ROUNDS_TEST_FLUTTER_BIN"))
    if native:
        checks.append(("native-identity-preservation-tests", ["python3", "tools/verify_v23_native.py"]))
        checks.append(("native-sqlcipher-process-kill-tests", ["python3", "tools/verify_v23_sqlcipher_crash.py"]))
    android_barrier = bool(env.get("ROUNDS_TEST_ANDROID_JAR"))
    if android_barrier:
        checks.append(("android-durability-barrier-tests", ["python3", "tools/verify_v23_android_barrier.py"]))
    android_build = env.get('ROUNDS_TEST_BUILD_ANDROID') == '1'
    if android_build:
        assert native, 'Android build requires ROUNDS_TEST_FLUTTER_BIN'
        checks.append(('android-arm64-debug-build', ['python3', 'tools/verify_v23_android_build.py']))
    OUT.mkdir(parents=True, exist_ok=True)
    source_before = hashes(SOURCE.rglob("*"))
    code = hashes([p for base in ["packages/contracts", "packages/domain-ts", "services/api/src", "services/api/test", "services/api/migrations", "apps/operations-web/src", "apps/operations-web/test", "apps/operations-web/app", "apps/driver_harness/lib", "apps/driver_harness/test", "apps/driver_harness/android/app/src"]
                   for p in (ROOT / base).rglob("*") if "node_modules" not in p.parts and "dist" not in p.parts]
                  + list((ROOT / "tools").glob("*.py")) + list((ROOT / "tools").glob("*.ts")) + list((ROOT / "tools").glob("*.mjs")) + [ROOT / "apps/operations-web/package.json", ROOT / "apps/operations-web/tsconfig.json", ROOT / "package-lock.json", ROOT / "services/api/package.json", ROOT / "services/api/tsconfig.json", ROOT / "tsconfig.base.json", ROOT / "apps/driver_harness/pubspec.yaml", ROOT / "apps/driver_harness/pubspec.lock"]
                  + [ROOT / "apps/driver_harness/android" / p for p in ["app/build.gradle.kts", "build.gradle.kts", "settings.gradle.kts", "gradle.properties", "gradle/wrapper/gradle-wrapper.properties"]])
    results = []
    for name, command in checks:
        started = datetime.now(timezone.utc).isoformat()
        limit = 600 if name == 'native-identity-preservation-tests' else 180
        try:
            run = subprocess.run(command, cwd=ROOT, env=env, capture_output=True, text=True, timeout=limit)
            output, code_value = run.stdout + run.stderr, run.returncode
        except subprocess.TimeoutExpired:
            output, code_value = f"TIMEOUT after {limit} seconds; not a passing check\n", 124
        log = OUT / f"run-{name}.txt"
        log.write_text(output)
        results.append({"name": name, "command": command, "started_utc": started,
                        "status": "PASS" if code_value == 0 else "FAIL", "exit_code": code_value,
                        "log": str(log.relative_to(ROOT)), "log_sha256": hashlib.sha256(log.read_bytes()).hexdigest()})
        print(f"{name}: {results[-1]['status']}", flush=True)
    assert source_before == hashes(SOURCE.rglob("*")), "A check mutated source files"
    report = {"recorded_utc": datetime.now(timezone.utc).isoformat(),
              "manual_intake_scope": "ADR-T09/Q08 implement restricted manual draft save/read, original CommandStatus and staged source-derived React draft recovery. ADR-T10 adds independent deliveries.review, exact current root/input hash, accept/edit/reject and immutable original/proposed/selected review history in isolated migration0010. Review increments effective revision and preserves original submitted data; no unconditional ready, entrance confirmation, delivery/admission/preparation/custody/assignment effect. Tests cover all decisions, stale/expired/foreign suggestions, original receipt/replay and lost Node HTTP response, competing review/save, rollback, restricted history RLS and capability/revocation boundaries. Auth/provider data is labelled synthetic; SQL/transactions and local HTTP are real isolated execution. Original HTML remains unchanged. Approved map-review UI binding, timing/admission/whole-order commit, configured provider/Auth/SQL, source pixel parity and phone activation remain open. Individual current check statuses, not this scope description, determine PASS.",
              "baseline_commit": "19d6c1e7dc570546026cfb41135fae74c6b4e23e",
              "working_revision": "2.3-r1", "source_files": source_before, "code_and_tool_files": code,
              "pickup_issue_recovery_read_scope": "ADR-Q04 adds restricted DriverRound view=pickup_issue and native original committed-report selectors/current-lease reads. Staged G03 report/reopen now hands the host a loading controller immediately while reading the original issue; explicit Refresh coalesces and never resends. Controller/route tests cover waiting/actual exact instructions/failed first read/last-known text, regressed versions, original queue preservation, scheduled/pending/completed reads across Auth changes, disposal, controller replacement and delayed/failed navigation. Real encrypted files; HTTP/Auth/vault are labelled doubles. Server tests cover actual registration/report/query, original actor/assignment/device/city denial, pure reads, held/waiting truth and immutable supersession/privacy/corruption. Reader corruption fixtures seed decisions; ADR-T08 separately tests actual wait/escalate writes into this query. Approved pre-pickup host recovery artwork, Dispatch controls and phone activation remain open. No permission to collect/continue follows from an instruction; no durable reply cache/schema migration is introduced.",
              "pickup_issue_decision_scope": "ADR-T08 implements Operations ResolveIssue wait/escalate only through verified-subject resolution, current city issues.decide capability, restricted pinned SQL and default-off HTTP/status. Actual ReportIssue→Operations decision→original Driver query tests cover reason/actor privacy, unchanged goods/readiness, duplicate replay, concurrent optimistic conflicts, original-assignment and archived-team denial, rollback after writes, immutable supersession and cross-actor/city/tenant isolation. Migration0008 preserves old-schema decision content with nullable reason and SELECT-only Operations report access; original actor-only INSERT and Driver identity UPDATE restrictions remain intact. Auth is a labelled double. Other decision actions, approved Dispatch/host recovery controls, configured provider and phone activation remain open. Current check statuses, not this scope text, determine PASS.",
              "pickup_issue_scope": "ADR-T07 supplies restricted pre-pickup ReportIssue/status, immutable original reports and conditional order/departure holds. ADR-M04 adds migration0007 original-report pickup-photo reservation/verification and attachment enforcement. ADR-S09 connects native missing/wait and damaged/wrong reports using original delivery versions, encrypted camera intent, shared signed PUT/status, verified photo materialization and explicit ReportIssue. Exact transfer receipt bindings avoid self-dependency or fake handoff. Native tests exercise real SQLCipher/files and production TS request/hash validation with labelled camera/HTTP/Auth/vault doubles; separate SQL/raster tests cover the backend. Current individual statuses/logs establish results, not this description. G03 editable encrypted form/camera candidates, source-sized choices/evidence view and explicit report route now exist as staged code. Tests cover retake/edit/restart/tamper/submission and original-status recovery. Source screenshot/font comparison, host decision/recovery UI, phone and configured-provider activation remain open.",
              "pickup_display_scope": "ADR-Q03 adds opt-in DriverRound view=pickup on the same restricted assigned-job transaction as the unchanged execution view: authorized names, manifest lines and real parcel contents, without contact secrets or inferred package IDs. Local PostGIS tests cover identity/job denial, decimal contents, missing/ambiguous labels and execution digest compatibility. Native generated parsing, authenticated current lease, encrypted FIRST-context preservation, late-response denial and the existing D03/D04 presentation adapter are tested with HTTP/Auth doubles. ADR-S08 adds encrypted collection/selection/intent and staged shared-view confirmation through the existing original-arrival queue. Actual SQLCipher/reopen, injected commit interruption, full quantities, repeated-tap deduplication, status-only loss/rejection/reassignment recovery and widget callbacks are tested. Waiting/review/unpacked destinations and G03 host activation, source/font comparison, main/phone cutover and configured end-to-end journey remain open. See individual logs/status.",
              "pod_asset_scope": "ADR-M02 adds ReserveAsset/VerifyAsset through the exact HTTP boundary and isolated migration0004's immutable handoff/actor/assignment binding (132 tables total: 131 reference plus binding). Real restricted SQL and registered arrival->pickup->arrival->handoff precede actual PNG/JPEG size/hash/full-decoding checks. Fresh staging capabilities never enter receipts; server-write-only sealed copies are reread before verification commits. IO revocation, receiver correction, rollback, replay and races are exercised. ADR-M03 adds the actual Supabase REST create-only private-object adapter and four-minute signed-PUT gateway, bounded Node ingress and explicit default-off isolated runtime. Its protocol tests and one complete restricted SQL workflow use labelled upstream REST/Auth doubles. No cloud account/policy configuration, scanner, signed viewer, retention cleanup or phone activation. Native sender scope is separately bounded below. See check logs/status for actual results.",
              "proof_completion_scope": "ADR-T06 restricted SubmitProof/CompleteDelivery: original assignment/receipt, captured policy, six proof kinds, immutable notes/arrival references/candidates, whole-order completion, claim archive and conditional Round/commitment release. Missing/invalid evidence, receiver correction, revoked scope, rollback/races/replay after closure, unfinished duties and multi-order query digest are tested. Migration0005 executes on fresh/prior proof-column fixtures without evidence backfill. No broker grant, customer send, provider/phone activation or Driver5 conversion. See logs/status for actual results.",
              "native_observation_scope": "Original contexts/camera observations use real SQLCipher/AES-GCM. ADR-S06/S07 add a linear arrival/pickup/handoff/single-photo/proof/completion queue: original-fence receipt bindings, exact bytes/hash, internal reserve/verify commands, ephemeral allowlisted signed PUT, lost-upload verification/status recovery, rollback/reopen, account/assignment and redirect/host/token/method denial. Actual eight native requests/hashes are checked with production TypeScript validators. Auth/HTTP/vault are doubles; encrypted files are real. Separate PostGIS suites execute server handlers/raster verification. Configured provider, signatures/multiple photos/candidates, branches, work discovery/UI, source-camera recovery, offline unlock, stale-retention and mobile migration/activation remain open. See statuses/logs.",
              "status": "PASS" if all(x["status"] == "PASS" for x in results) else "FAIL", "checks": results,
              "operations_issue_scope": "ADR-Q05 finite Board pickup_issues under current issues.decide and original ReportIssue scope. Shared eligibility and actual latest instructions; no private reason/device identity/media URL. Opt-in display=labels adds authorized nullable current delivery reference, recipient/address, site and original reporting driver; old response keys remain unchanged without opt-in. Restricted-role tests check missing/ambiguous/archived/foreign labels and reassignment suppression. Browser labels never enter the draft journal or rebase commands. Controller uses generated static validators, bounded/coalesced reads, last-known failures and exact immutable status-first retry. Tab/login recovery saves drafts/frozen bytes before POST; fresh authorization precedes hydration, storage/conflict/settlement failures block new sends, version floors survive recreation and Auth cleanup is narrow. Actual client->Node->restricted SQL->Driver tests inject lost responses with/without controller recreation and require one POST. React source-derived cards/detail/reply form and default-off verified-login host exist; the legacy/full Phase39 board is not switched. Browser component evidence is separately recorded with explicitly synthetic HTTP/Auth, not configured provider/SQL/phone acceptance or actual dirty-browser reload. Original interactive-source parity, secure evidence viewing and full-board integration remain open. No new migration, legacy-data or source-artwork changes. Operations source/app/test/configuration and generators are fingerprinted.",
              "operations_delivery_board_scope": "ADR-Q06 Board delivery_board uses board.read separate from issues.decide, exact tenant/city/date and restricted repeatable-read facts. Actual labels/raw states/stored point provenance and unique current-manifest planning reference; no inferred category counts, receipt, GPS or fleet. Bounds200rows/1MiB fail without truncation. Real PostgreSQL/HTTP and read-only adapter->Node->SQL tests check privacy, revocation, scope, snapshot/no-writes, pre-arrival/unplanned orders, null/zero points, inactive links, duplicate-stop constraint and bounds. Browser adapter tests check static validation, coalescing, last-known failures, immutable data, regression, late Auth/disposal and cancellation. Default-off verified-login Dispatch host now mounts delivery cards, provided context labels, local search and limited read-only details in source-derived Phase39 geometry. Independent report reader/reply journal remains intact; scope mismatch hides both and Auth disposes both. Added render/presentation tests and separately recorded synthetic browser checks cover missing labels, date/timezone, stale/empty/denied reads, selection, responsive surfaces and report-draft preservation. Now/Plan classification, full detail/actions and planning remain unfinished, not filled with prototype data. Map adapter scope is separately recorded. Provider Auth is a double in database/browser fixtures; configured Auth/SQL host, original pixel parity, shared migration and phone activation remain unaccepted. No schema, source artwork or earlier wire changes.",
              "operations_map_scope": "Mapbox SDK adapter and source-derived Phase39 Operations/Satellite/3D Site menu, rotation20/North, fit/focus, native zoom/compass and stored destination markers are connected to the authorized delivery reader. Public-token allowlist has no prototype fallback; no flags enabled. Tests exercise projection/zero/dateline/invalid coordinates, immutable camera/selection, style races, initial/style timeout, provider failure/retry and revoked/late cleanup with a labelled map-port double. Browser evidence uses the real React/controller with that explicit synthetic port: it is not live SDK, basemap, imagery or account acceptance. No routes/GPS/weather/traffic/verified entrances or command writes are invented. Exact controls/CSS/icon paths are source-linked. Configured Mapbox/Auth/SQL browser journey, attribution under actual SDK rendering, full source parity and phone activation remain unaccepted. No schema/legacy data/source artwork changes.",
              "operations_now_scope": "ADR-Q07 extends the original Q06 read-only delivery-board checkpoint with opt-in display=now. Same restricted repeatable-read snapshot adds exact one-per-delivery finite categories/reasons and the current city-local day; legacy responses are unchanged. Issue/outcome/current-unit/attempt/assignment facts drive Action/Ready/On road/Done; collected custody is not GPS movement and Ready is not mutation authority. React Phase39 tabs/counts/search/brand share the server projection; current day switches retain the remembered Plan date and original pickup-report drafts. Unknown/planned work remains in Show all, not falsely Ready. Focused PostGIS tests include an actual restricted pickup crossing Ready->On road, read-only seeded handoff/completion cases, same-scope issue precedence, archival/isolation, no writes and adapter->HTTP->SQL. Browser fixture uses labelled synthetic HTTP/Auth/map, not configured provider data. Full detail/action commands, intake/planning writes, source pixel parity and phone activation remain unfinished. See individual check results; no schema/grant/legacy-storage migration, source artwork change, shared deployment or phone cutover.",
              "operations_dispatch_action_scope": "The first bounded Action workflow joins current-city-day issue-category delivery IDs to independently authorized, fresh pickup reports under identical principal/session/tenant/city/date. No names, new assignees or Round-only guesses. Existing card->detail->report->wait/escalate form is reused; a single match opens review, multiple direct reports require selection. Saved drafts and pending original bytes are never replaced. Confirmed settlement refreshes the delivery reader without optimistic hold/readiness changes. New unit/render checks and actual client->local Node->restricted SQL->Driver tests exercise both replies, one-POST uncertain-result recovery and permission revocation. Synthetic compiled-React browser evidence is separate from configured provider/Auth/SQL/phone and original-source pixel parity. Other Action reasons, full planning and installed-client activation remain open; no schema, wire, source artwork, shared data or deployment change.",
              "harness_note": "node --import tsx avoids the tsx CLI IPC socket. Native PostgreSQL tests require permission for a loopback listener; initial sandbox EPERM was a setup failure, not a passing/skipped test. The fixture creates/removes only its own temporary cluster, with no Supabase URL or host-user creation.",
              "database_executed": "Native PostgreSQL17.10 foundation: five actual source tables plus selected RLS, local receipt migration and synthetic authorization/domain probes. Real receipt races/locks/rollback; SQLSTATE retry and lost-COMMIT transport failures injected and labelled. " + ("Full PostgreSQL17/PostGIS fixture also requested: all131tables/five source SQL files plus isolated identity/job-scope and device-installation migrations, guards/probes, actual registration/refresh/revocation and query->pickup arrival->whole pickup->dropoff arrival->handoff with predecessor versions. ConfirmArrival tests cover quality/policy override, current stop/attempt, causal timestamps, replay/status and atomic rollback. Older handoff tests still seed pickup-arrival setup but use the actual dropoff arrival endpoint. The POD suite covers proof/completion. Server stale-retention and phone/provider activation are not claimed. Auth/GPS are synthetic; SQL principal/device/job/receipt and localhost HTTP are real. Runtime and hashes in run-full-postgis-schema-tests.txt. See individual status, not this description, for pass/fail." if full_postgis else "Full PostGIS fixture NOT_RUN: ROUNDS_TEST_PG_BIN not configured."),
              "native_evidence": "HTTP/Auth and key vault mocked. Actual SQLCipher/AES-GCM bytes, account isolation, staged-file recovery and private fsync/flock in temporary macOS fixtures. Separate actual SIGKILL/hot-journal rollback and cross-process writer exclusion. Actual Driver5 encrypted unassigned DB/draft/media preservation with injected copy interruption/source recheck; legacy outbox/upload regressions. Lifecycle composition plus default-off main/controller/DriverApi connection: actual controller/DB cold-start guards, delayed OTP/refresh/native token-write races, HTTP denial, same-token coalescing and lock-only Auth expiry. Android root/backup compile/package checks are separate from OS execution. No configured Auth, mobile vault/backup, hot migration, camera/offline/sender cutover, account import/replay or phone installation. " + ("Requested; see native test and process-kill results/logs." if native else "NOT_RUN: ROUNDS_TEST_FLUTTER_BIN absent."),
              "not_run": ([] if full_postgis else ["Full PostgreSQL/PostGIS fixture"]) + ([] if native else ["Native identity/preservation/encryption tests"]) + ([] if android_barrier else ["Android barrier Java compilation/ordering tests"]) + ([] if android_build else ["Android ARM64 debug APK/Activity build"]) + ["All business handlers/role permutations and Supabase Auth/Realtime", "Full TS/Dart HTTP clients", "Shared DB migration/cutover", "Actual mobile Keychain/Keystore/backup, paused legacy writers and authorized account import/replay", "Actual process kill during the legacy archive converter", "OS disk barrier kill/full-disk tests on mobile devices; iOS/other ABI/release packaging",
                          "Browser screenshot parity", "Phone workflow", "Real provider effects"],
              "meaning": "Local source/metadata/wire/unit/type checks, PostgreSQL foundation, full-schema probes, explicit own-team arrival, first-local pickup, whole-order handoff and isolated HTTP boundary. The arrival suite uses real query/arrival/pickup/handoff handlers; proof/completion runs in the POD suite; server stale-retention remains open. Provider Auth and GPS are synthetic; older tests seed devices, new tests use registration-issued credentials. Native credential/preflight, macOS SQLCipher/AEAD bytes and process-kill checks plus legacy encrypted quarantine copy tests are separate from mobile vault/backup, configured Auth/Realtime, authorized account mapping, phone or deployment. Not all arrival/pickup variants,131commands,197acceptance cases, full W01.2 exit or product completion."}
    (OUT / "test-results.json").write_text(json.dumps(report, indent=2) + "\n")
    return report["status"] != "PASS"


if __name__ == "__main__":
    raise SystemExit(main())
